In [1]:
import sys
sys.path.insert(0, '../')

In [2]:
import json
import pandas as pd
import numpy as np
from src.agent import Pipeline, PipelineAgentConfig, IOAgent, AgentContext, registry
from src.llm_client import LLMClient
from src.schema.llm_config import LLMConfig
from src.utils.data import SyntheticEmotionDataset, EmpatheticDialoguesDataset

In [3]:
TEST_PART_SIZE = 200

In [4]:
with open("../configs/llm_generation/gpt_4o_mini_config.json", "r") as f:
    config_dct = json.load(f)
llm_config = LLMConfig.from_dict(config_dct)
llm_client = LLMClient(llm_config)

In [5]:
dset = SyntheticEmotionDataset("../data/synthetic_dialogues/v2/dialogues.json", "../data/synthetic_dialogues/v2/scenarios.json")

In [6]:
gt_emotion = [dset[i].emotion.value for i in range(TEST_PART_SIZE)]

In [7]:
with open("../data/baseline_erc_bert.json", "r") as f:
    data = json.load(f)["predictions"]

In [8]:
def get_argmax(res):
    keys = list(res.keys())
    values = list(res.values())
    index_max = np.argmax(values)
    return keys[index_max]

In [9]:
baseline_predictions = [get_argmax(item['prediction']) for item in  data[:TEST_PART_SIZE]]

In [10]:
with open("../data/inside_out_erc_results.json", "r") as f:
    data = json.load(f)["predictions"]

In [11]:
predictions_inside_out = [item['prediction'].split('; ')[0].lower() for item in data]

In [12]:
with open("../data/gptswarm_agent_erc_exp2_result_gpt4o-mini.json", "r") as f:
    data = json.load(f)["predictions"][:200]

In [13]:
predictions_gptswarm = [item['prediction'].split('; ')[0].lower() for item in data]

In [14]:
with open("../data/gptswarm_agent_erc_random_result_gpt4o-mini.json", "r") as f:
    data = json.load(f)["predictions"][:200]

In [15]:
predictions_gptswarm_rand = [item['prediction'].split('; ')[0].lower() for item in data]

In [17]:
with open("../data/inside_out_alt_topology_exp_03_30_25.json", "r") as f:
    data = json.load(f)["predictions"]

In [18]:
predictions_inside_out_alt_topology_v1 = [item['prediction'].split('; ')[0].lower() for item in data]

In [19]:
with open("../data/inside_out_alt_topology_v2_debug.json", "r") as f:
    data = json.load(f)["predictions"]

In [20]:
predictions_inside_out_alt_topology_v2 = [item['prediction'].split('; ')[0].lower() for item in data]

In [21]:
def accuracy(gt, pred):
    mask = [u == v for u, v in zip(gt, pred)]
    return np.array(mask).mean()

In [22]:
results = {
    "bert baseline": accuracy(gt_emotion, baseline_predictions),
    "inside-out": accuracy(gt_emotion, predictions_inside_out), 
    "inside-out alt_topology_v1": accuracy(gt_emotion, predictions_inside_out_alt_topology_v1),
    "inside-out alt_topology_v2": accuracy(gt_emotion, predictions_inside_out_alt_topology_v2),
    "gptswarm optimized": accuracy(gt_emotion, predictions_gptswarm), 
    "gptswarm random": accuracy(gt_emotion, predictions_gptswarm_rand)
}
results_df = pd.DataFrame([results])
results_df

,bert baseline,inside-out,inside-out alt_topology_v1,inside-out alt_topology_v2,gptswarm optimized,gptswarm random
0,0.645,0.735,0.715,0.7,0.8,0.625

In [20]:
dset = EmpatheticDialoguesDataset("../data/empatheticdialogues", "test")

In [21]:
gt_emotion = [dset[i].emotion.value for i in range(len(dset))]

In [22]:
with open("../data/empatheticdialogues_test_baseline_erc_bert.json", "r") as f:
    data = json.load(f)["predictions"]

In [23]:
baseline_predictions = [get_argmax(item['prediction']) for item in  data]

In [24]:
with open("../data/empatheticdialogues_test_inside_out_erc_results.json", "r") as f:
    data = json.load(f)["predictions"]

In [25]:
predictions_inside_out = [item['prediction'].split('; ')[0].lower() for item in data]

In [26]:
with open("../data/empatheticdialogues_test_inside_out_alt_topology_exp1.json", "r") as f:
    data = json.load(f)["predictions"]

In [27]:
predictions_inside_out_alt_topology_v1 = [item['prediction'].split('; ')[0].lower() for item in data]

In [29]:
with open("../data/empatheticdialogues_test_gptswarm_erc_exp2_result_gpt4o-mini.json", "r") as f:
    data = json.load(f)["predictions"]

In [30]:
predictions_gptswarm = [item['prediction'].split('; ')[0].lower() for item in data]

In [31]:
results = {
    "bert baseline": accuracy(gt_emotion, baseline_predictions),
    "inside-out": accuracy(gt_emotion, predictions_inside_out), 
    "inside-out alt_topology_v1": accuracy(gt_emotion, predictions_inside_out_alt_topology_v1),
    "gptswarm": accuracy(gt_emotion, predictions_gptswarm)
}
results_df = pd.DataFrame([results])
results_df

   bert baseline  inside-out  inside-out alt_topology_v1  gptswarm
0       0.767372     0.81571                    0.809668  0.776667

In [22]:
from src.agent import registry

In [25]:
conf = registry.get_config("inside-out-erc")

In [47]:
TEST_PART_SIZE = 300

In [48]:
dset = EmpatheticDialoguesDataset("../data/empatheticdialogues", "test", extended=True)
gt_emotion = [dset[i].emotion.value for i in range(TEST_PART_SIZE)]

In [11]:
with open("../data/empatheticdialogues_test_inside_out_erc_extended_emotions_results.json", "r") as f:
    data = json.load(f)["predictions"][:200]

In [12]:
predictions_inside_out = [item['prediction'].split('; ')[0].lower() for item in data]

In [13]:
with open("../data/empatheticdialogues_test_inside_out_erc_extended_emotions_results_gpt4o.json", "r") as f:
    data = json.load(f)["predictions"][:300]

In [14]:
predictions_inside_out_gpt4o = [item['prediction'].split('; ')[0].lower() for item in data]

In [53]:
with open("../data/empatheticdialogues_test_gptswarm_erc_exp2_result_gpt4o_extended.json", "r") as f:
    data = json.load(f)["predictions"][:300]

predictions_gptswarm = []
for item in data:
    try:
        predictions_gptswarm.append(item['prediction'].split('FINAL ANSWER: ')[1].split(';')[0].lower())
    except:
        predictions_gptswarm.append('')

In [68]:
results = {
    "inside out": accuracy(gt_emotion, predictions_inside_out),
    "inside out gpt4o": accuracy(gt_emotion, predictions_inside_out_gpt4o),
    "GPTSwarm": accuracy(gt_emotion, predictions_gptswarm),
    "GPTSwarm random": 0.123, 
}
results_df = pd.DataFrame([results])
results_df

   inside out  inside out gpt4o  GPTSwarm  GPTSwarm random
0       0.215          0.413333  0.406666            0.123

In [ ]:
with open("../data/empatheticdialogues_test_gptswarm_agent_erc_extended_emotions_results.json", "r") as f:
    data = json.load(f)["predictions"][:200]

In [33]:
conf.agent_configs

[{'agent_type': 'Echo', 'agent_id': 'input'},
 {'agent_type': 'IO',
  'agent_id': 'anger_agent',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Anger. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"},
   {'role': 'user', 'content': 'Dialogue:\n{input}.'}]},
 {'agent_type': 'IO',
  'agent_id': 'disgust_agent',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Disgust. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"},
   {'role': 'user', 'content': 'Dialogue:\n{input}.'}]},
 {'agent_type': 'IO',
  'agent_id': 'fear_agent',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Fear. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"},
   {'role': 'user', 'content': 'Dialogue:\n{input}.'}]},
 {'agent_type': 'IO',
  'agent_id': 'happiness_agent',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Happiness. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"},
   {'role': 'user', 'content': 'Dialogue:\n{input}.'}]},
 {'agent_type': 'IO',
  'agent_id': 'sadness_agent',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Sadness. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"},
   {'role': 'user', 'content': 'Dialogue:\n{input}.'}]},
 {'agent_type': 'IO',
  'agent_id': 'aggregator',
  'messages': [{'role': 'system',
    'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou have been given answers by several emotional agents, each of whom was interviewed to assess the emotional state of the first (A) interlocutor in the dialogue.\nYou are also given the dialogue itself.\nYour task is to aggregate the responses of these agents and give your own based on the dialogue and the responses of the agents.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`\nThe same format is followed for agent responses."},
   {'role': 'user',
    'content': 'Dialogue:\n{input}\nAgent responses:\n* {anger_agent}\n* {disgust_agent}\n* {fear_agent}\n* {happiness_agent}\n* {sadness_agent}'}]}]

In [31]:
res = []
for agent in conf.agent_configs:
    res.ap

{'agent_type': 'Echo', 'agent_id': 'input'}
{'agent_type': 'IO', 'agent_id': 'anger_agent', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Anger. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"}, {'role': 'user', 'content': 'Dialogue:\n{input}.'}]}
{'agent_type': 'IO', 'agent_id': 'disgust_agent', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Disgust. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"}, {'role': 'user', 'content': 'Dialogue:\n{input}.'}]}
{'agent_type': 'IO', 'agent_id': 'fear_agent', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Fear. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"}, {'role': 'user', 'content': 'Dialogue:\n{input}.'}]}
{'agent_type': 'IO', 'agent_id': 'happiness_agent', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Happiness. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"}, {'role': 'user', 'content': 'Dialogue:\n{input}.'}]}
{'agent_type': 'IO', 'agent_id': 'sadness_agent', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou feel Sadness. Act based on what emotion you are experiencing.\nYou need to assess emotion of the first (A) interlocutor in the dialogue, estimate your confidence and give reasoning for your answer.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`"}, {'role': 'user', 'content': 'Dialogue:\n{input}.'}]}
{'agent_type': 'IO', 'agent_id': 'aggregator', 'messages': [{'role': 'system', 'content': "You are a highly advanced language model.\nCarefully heed the user's instructions.\nYou have been given answers by several emotional agents, each of whom was interviewed to assess the emotional state of the first (A) interlocutor in the dialogue.\nYou are also given the dialogue itself.\nYour task is to aggregate the responses of these agents and give your own based on the dialogue and the responses of the agents.\nYour answer should consist of an emotion and an assessment of the level of confidence in it in the range from 0 to 1.\nTo select emotions, use Ekman's classification into 5 main emotions - Anger, Disgust, Fear, Happiness, Sadness.\nSeparate the emotion and the response using a semicolon.\nResponse example:\n`Anger; 0.7`\nThe same format is followed for agent responses."}, {'role': 'user', 'content': 'Dialogue:\n{input}\nAgent responses:\n* {anger_agent}\n* {disgust_agent}\n* {fear_agent}\n* {happiness_agent}\n* {sadness_agent}'}]}